name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        run: |
          docker build \
            --build-arg NEW_RELIC_LICENSE_KEY="${{ secrets.NEW_RELIC_LICENSE_KEY }}" \
            --build-arg NEW_RELIC_APP_NAME="PHUKIENweb" \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/phpweb-phukien:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/phpweb-phukien:latest

